version: "3.6"
services:
        spark-master:
                image: spark-master:v3
                container_name: spark-master
                hostname: spark-master
                ports:
                        - "8080:8080"
                        - "7077:7077"
                networks: 
                        spark-network:
                                ipv4_address: 10.1.1.2
                volumes:
                        - /Users/marvinlandicho/build/spark-cluster/apps:/opt/spark-apps
                        - /Users/marvinlandicho/build/spark-cluster/data:/opt/spark-data
                environment:
                        - "SPARK_LOCAL_IP=spark-master"
        spark-worker-1:
                image: spark-worker:v3
                container_name: spark-worker-1
                hostname: spark-worker-1
                depends_on:
                        - spark-master
                ports:
                        - "8081:8081"
                env_file: ./env/spark-worker.sh
                environment:
                        - "SPARK_LOCAL_IP=spark-worker-1"
                networks: 
                        spark-network:
                                ipv4_address: 10.1.1.3
                volumes:
                        - /Users/marvinlandicho/build/spark-cluster/apps:/opt/spark-apps
                        - /Users/marvinlandicho/build/spark-cluster/data:/opt/spark-data
        spark-worker-2:
                image: spark-worker:v3
                container_name: spark-worker-2
                hostname: spark-worker-2
                depends_on:
                        - spark-master
                ports:
                        - "8082:8081"
                env_file: ./env/spark-worker.sh
                environment:
                        - "SPARK_LOCAL_IP=spark-worker-2"
                networks:
                        spark-network:
                                ipv4_address: 10.1.1.4
                volumes:
                        - /Users/marvinlandicho/build/spark-cluster/apps:/opt/spark-apps
                        - /Users/marvinlandicho/build/spark-cluster/data:/opt/spark-data
        spark-worker-3:
                image: spark-worker:v3
                container_name: spark-worker-3
                hostname: spark-worker-3
                depends_on:
                        - spark-master
                ports:
                        - "8083:8081"
                env_file: ./env/spark-worker.sh
                environment:
                        - "SPARK_LOCAL_IP=spark-worker-3"
                networks: 
                        spark-network:
                                ipv4_address: 10.1.1.5
                volumes:
                        - /Users/marvinlandicho/build/spark-cluster/apps:/opt/spark-apps
                        - /Users/marvinlandicho/build/spark-cluster/data:/opt/spark-data
networks:
        spark-network:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 10.1.1.0/24
